const products = [
    { id: 1, name: "Wireless Earbuds", description: "Noise-cancelling wireless earbuds.", price: 49.99, imageUrl: "https://via.placeholder.com/150" },
    { id: 2, name: "Smart Watch", description: "Water-resistant smart watch.", price: 129.99, imageUrl: "https://via.placeholder.com/150" },
    { id: 3, name: "Laptop Backpack", description: "Ergonomic laptop backpack.", price: 39.99, imageUrl: "https://via.placeholder.com/150" },
    { id: 4, name: "Gaming Mouse", description: "High-precision gaming mouse.", price: 29.99, imageUrl: "https://via.placeholder.com/150" },
    { id: 5, name: "Bluetooth Speaker", description: "Portable Bluetooth speaker.", price: 59.99, imageUrl: "https://via.placeholder.com/150" },
    { id: 6, name: "Fitness Tracker", description: "Activity and sleep tracker.", price: 74.99, imageUrl: "https://via.placeholder.com/150" },
    { id: 7, name: "4K Monitor", description: "Ultra HD 4K monitor.", price: 399.99, imageUrl: "https://via.placeholder.com/150" },
    { id: 8, name: "Mechanical Keyboard", description: "RGB mechanical keyboard.", price: 89.99, imageUrl: "https://via.placeholder.com/150" },
    { id: 9, name: "VR Headset", description: "Virtual reality headset.", price: 299.99, imageUrl: "https://via.placeholder.com/150" },
    { id: 10, name: "Wireless Charger", description: "Fast wireless charging pad.", price: 19.99, imageUrl: "https://via.placeholder.com/150" },
    { id: 11, name: "Smartphone Gimbal", description: "Stabilizer for smartphone videos.", price: 99.99, imageUrl: "https://via.placeholder.com/150" },
    { id: 12, name: "Portable SSD", description: "1TB external portable SSD.", price: 149.99, imageUrl: "https://via.placeholder.com/150" },
    { id: 13, name: "Smart Light Bulb", description: "Wi-Fi enabled smart bulb.", price: 14.99, imageUrl: "https://via.placeholder.com/150" },
    { id: 14, name: "Action Camera", description: "4K waterproof action camera.", price: 199.99, imageUrl: "https://via.placeholder.com/150" },
    { id: 15, name: "Noise Cancelling Headphones", description: "Over-ear noise cancelling headphones.", price: 249.99, imageUrl: "https://via.placeholder.com/150" },
    { id: 16, name: "Smart Thermostat", description: "Wi-Fi enabled smart thermostat.", price: 199.99, imageUrl: "https://via.placeholder.com/150" },
    { id: 17, name: "Drone", description: "4K camera drone with GPS.", price: 599.99, imageUrl: "https://via.placeholder.com/150" },
    { id: 18, name: "Robot Vacuum", description: "Smart robot vacuum cleaner.", price: 299.99, imageUrl: "https://via.placeholder.com/150" },
    { id: 19, name: "Smart Doorbell", description: "Video doorbell with motion detection.", price: 149.99, imageUrl: "https://via.placeholder.com/150" },
    { id: 20, name: "Electric Toothbrush", description: "Rechargeable electric toothbrush.", price: 79.99, imageUrl: "https://via.placeholder.com/150" },
    { id: 21, name: "Tablet", description: "10-inch HD display tablet.", price: 249.99, imageUrl: "https://via.placeholder.com/150" },
    { id: 22, name: "Gaming Chair", description: "Ergonomic gaming chair.", price: 199.99, imageUrl: "https://via.placeholder.com/150" },
    { id: 23, name: "Smart Scale", description: "Bluetooth body composition scale.", price: 49.99, imageUrl: "https://via.placeholder.com/150" },
    { id: 24, name: "Laptop Stand", description: "Adjustable aluminum laptop stand.", price: 29.99, imageUrl: "https://via.placeholder.com/150" },
    { id: 25, name: "Phone Tripod", description: "Flexible phone tripod.", price: 24.99, imageUrl: "https://via.placeholder.com/150" },
    { id: 26, name: "Wireless Mouse", description: "Rechargeable wireless mouse.", price: 19.99, imageUrl: "https://via.placeholder.com/150" },
    { id: 27, name: "Smart Plug", description: "Wi-Fi smart plug.", price: 12.99, imageUrl: "https://via.placeholder.com/150" },
    { id: 28, name: "USB-C Hub", description: "Multiport USB-C adapter.", price: 39.99, imageUrl: "https://via.placeholder.com/150" },
    { id: 29, name: "Streaming Stick", description: "4K streaming media player.", price: 49.99, imageUrl: "https://via.placeholder.com/150" },
    { id: 30, name: "Coffee Maker", description: "Single-serve coffee maker.", price: 89.99, imageUrl: "https://via.placeholder.com/150" },
    { id: 31, name: "Smart Air Purifier", description: "HEPA air purifier with app control.", price: 129.99, imageUrl: "https://via.placeholder.com/150" },
    { id: 32, name: "Bluetooth Keyboard", description: "Compact Bluetooth keyboard.", price: 29.99, imageUrl: "https://via.placeholder.com/150" },
    { id: 33, name: "Smart Lock", description: "Keyless entry smart lock.", price: 199.99, imageUrl: "https://via.placeholder.com/150" },
    { id: 34, name: "E-Reader", description: "Waterproof e-reader with backlight.", price: 139.99, imageUrl: "https://via.placeholder.com/150" },
    { id: 35, name: "Desk Lamp", description: "LED desk lamp with USB charging.", price: 39.99, imageUrl: "https://via.placeholder.com/150" },
    { id: 36, name: "Portable Power Bank", description: "10000mAh portable charger.", price: 24.99, imageUrl: "https://via.placeholder.com/150" },
    { id: 37, name: "Projector", description: "1080p portable projector.", price: 299.99, imageUrl: "https://via.placeholder.com/150" },
    { id: 38, name: "Smart Camera", description: "Indoor security camera with motion detection.", price: 79.99, imageUrl: "https://via.placeholder.com/150" },
    { id: 39, name: "Smart Fan", description: "Wi-Fi enabled smart fan.", price: 149.99, imageUrl: "https://via.placeholder.com/150" },
    { id: 40, name: "Electric Kettle", description: "Smart electric kettle with temperature control.", price: 59.99, imageUrl: "https://via.placeholder.com/150" },
];

export default products;
